version: '3.4'
services:

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./http-test-suite:/var/www/html
      - ./httpd.conf:/etc/httpd.conf
    expose:
      - "80"
    ports:
    - "80:80"